name: build documentation

on: 
  pull_request:
    branches: [main]


jobs:  
  build-docs:
    runs-on: appsmgr-bruno
    steps:
      - uses: actions/checkout@v4
      - name: Build Docs
        run: |
          set +e
          pwd
	  hostname
	  . /etc/profile
	  module load anaconda
	  conda create --prefix ./env python=3.8
	  conda activate /env
	  pip install -y requirements.txt
	  mkdocs build
	  
